export const ActionTypes = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',

    LOGIN_CHANGED: 'LOGIN_CHANGED',
    PASSWORD_CHANGED: 'LOGIN_PASSWORD_CHANGED',
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
    LOGOUT: 'LOGOUT_USER',

    REGISTER_LOGIN_CHANGED: 'REGISTER_LOGIN_CHANGED',
    REGISTER_PASSWORD_CHANGED: 'REGISTER_PASSWORD_CHANGED',
    REGISTER_CONFIRM_PASSWORD_CHANGED: 'REGISTER_CONFIRM_PASSWORD_CHANGED',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
    REGISTER_CHECK_PASSWORD: 'REGISTER_CHECK_PASSWORD'
}